<h1>Editando Livro</h1>

<?php

$form = $this->form;

$form->setAttribute('action',$this->url('livraria-admin-interna',array('controller' => 'livro','action' => 'edit')));

$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('nome')) . '<br/><br/>';
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
