<h1>Livros</h1>

<table class="table">
    <thead>
    <th>Id</th>
    <th>Nome</th>
    <th>Categoria</th>
    <th>ISBN</th>
    <th>Valor</th>
    <th>Acao</th>
</thead>

<tbody>  

    <?php foreach ($this->data as $entity): ?>
        <tr>
            <td>
                <?= $entity->getId(); ?>
            </td>
            <td>
                <?= $entity->getNome(); ?>
            </td>
            <td>
                <?= $entity->getCategoria(); ?>
            </td>
            <td>
                <?= $entity->getIsbn(); ?>
            </td>
            <td>
                <?= $entity->getValor(); ?>
            </td>
            <td>
                <a class="btn btn-success" href="<?= $this->url('livraria-admin-interna',
                        array('controller' => 'livro', 'action' => 'edit', 'id' => $entity->getId())); ?>">
                    Editar
                </a>
                <a class="btn btn-success" href="<?= $this->url('livraria-admin-interna',
                        array('controller' => 'livro', 'action' => 'delete', 'id' => $entity->getId())); ?>">
                    Deletar
                </a>
            </td>
        </tr>
    <?php endforeach; ?>

</tbody>
</table>

<?php echo $this->paginationControl($this->data,'Sliding','paginator'); ?>


<a class="btn btn-success" href="<?= $this->url('livraria-admin',array('controller' => 'livro' , 'action' => 'new'));?>">Novo Livro</a>
