<h1>Novo Livro</h1>

<?php
$form = $this->form;

$form->setAttribute('action', $this->url('livraria-admin', array('controller' => 'livro', 'action' => 'new')));

$form->prepare();

echo $this->form()->openTag($form);
?>

<?= $this->formHidden($form->get('id')); ?>

<div class="form-group">
    <label for="nome">Nome</label>
    <?= $this->formRow($form->get('nome')); ?>
</div>

<div class="form-group">
    <?= $this->formRow($form->get('categoria')); ?>
</div>

<div class="form-group">
    <?= $this->formRow($form->get('autor')); ?>
</div>
<div class="form-group">
    <?= $this->formRow($form->get('valor')); ?>
</div>
<div class="form-group">
    <?= $this->formRow($form->get('isbn')); ?>
</div>
<div class="form-group">
    <?= $this->formSubmit($form->get('submit')); ?>
</div>
<?= $this->form()->closeTag(); ?>