<?php
$urlPattern = $_SERVER['REQUEST_URI'];
$formatUrl = function($page) use($urlPattern) {
    if (!preg_match('/page/', $urlPattern)) {
        return $urlPattern . '/page/' . $page;
    } else {
        return preg_replace('/\d/', $page, $urlPattern);
    }
};
?>

<center>
    <?php if ($this->pageCount) : ?>
        <div class="paginationControl">
            <?php echo $this->current; ?> - <?php echo $this->last; ?> de <?php echo $this->pageCount; ?>
            <br />

            <?php if (isset($this->previous)): ?>
                <a href="<?php echo $formatUrl($this->first) ?>">Primeira</a>
            <?php else: ?>
                <span class="disabled">Primeira</span>
            <?php endif ?>

            <?php if (isset($this->previous)): ?>
                <a href="<?php echo $formatUrl($this->previous) ?>">< Anterior</a>
            <?php else: ?>
                <span class="disabled">< Anterior</span>
            <?php endif ?>

            <?php if (isset($this->next)): ?>
                <a href="<?php echo $formatUrl($this->next) ?>">Proximo ></a>
            <?php else: ?>
                <span class="disabled">Proximo ></span>
            <?php endif ?>

            <?php if (isset($this->next)): ?>
                <a href="<?php echo $formatUrl($this->last) ?>">Ultimo ></a>
            <?php else: ?>
                <span class="disabled">Ultimo</span>
            <?php endif ?>


        </div>
    <?php endif ?>
</center>
